### PR TITLE
feat: support using the osv.dev api directly

### PR DESCRIPTION
**Pull request by G-Rath**
This adds support for using the osv.dev api directly - while currently this makes checking slower and prevents offline use, it means that we should be able to report vulnerabilities based on commits rather than versions.

This is very powerful since not all ecosystems support versions, and some ecosystems will casually use git-based dependencies (eg. `composer`).

The implementation itself should hopefully be pretty solid (though I've not done any tidying up), but I have to think more about how this should work from a defaults POV - I think the ideal would be to default to the api as in theory that should have the most up-to-date information (and is more powerful) but right now it looks like it's not 1:1 with the databases (which I suspect is a bug).

I also need to think about how it'll impact other features, such as CSV input.

Currently this does make the checking a lot slower because we have to make an API request for each package (typically takes about ~10 seconds for a modest `package-lock.json`), but that should hopefully be solved when osv.dev finish implementing their bulk endpoint.

### CODE REVIEW

**Comment by oliverchang** [comment]
> Currently this does make the checking a lot slower because we have to make an API request for each package (typically takes about ~10 seconds for a modest package-lock.json), but that should hopefully be solved when osv.dev finish implementing their bulk endpoint.

FYI this is ready on our staging API: https://github.com/google/osv/issues/321#issuecomment-1127177097

**Comment by G-Rath** [comment]
@oliverchang I've refactored this to be both just a generally cleaner implementation between the two database types, and for the api database to use the bulk endpoint but it looks like it's just returning the vulnerability IDs (which tracks with [your comment here](https://github.com/google/osv/issues/321#issuecomment-1058601580) but doesn't match with what the api documentation says).

This means it's not suitable by itself - I'm going to do another refactor to see what it's like if we try and fill the data we need using the `GET /v1/vulns/{id}` endpoint, but it might just be better to stick with using the single-package endpoint.

(I don't view the speed or amount of requests as a dealbreaker - it's still plenty fast, especially compared to the time taken to setup alternative tools and package managers)

**Comment by G-Rath** [comment]
hmm this could just be me but it feels like the bulk + `GET /v1/vulns/{id}` endpoint is actually slower than using the single package endpoint - I've not implemented parralisation for the `GET`s so it could be that. Will do that next

**Comment by G-Rath** [comment]
Ok I think this has done it - now I'm constantly getting ~6 seconds for a large `package-lock.json`.

**Comment by oliverchang** [comment]
> Ok I think this has done it - now I'm constantly getting ~6 seconds for a large `package-lock.json`.

Awesome!!!! Thanks for working on this.

**Comment by G-Rath** [comment]
Alright I think this is pretty much ready to go, though I did remember when writing the documentation that this adds `Commit` to `PackageDetails` which was right at the start so I want to do some checks on that (mainly its impact on the json output and see what planning is needed for modifying the manifest parsers to extract that information)

**Comment by G-Rath** [comment]
I also want to think about how this ties in with ##93 as I think that'll make this twice as useful since you'll be able to just provide arbitrary commits (which you can do with `curl`, but this way you'd get a nice parsed output rather than having to look through raw json).

tbh since you just need the commit, it's probably best to just have another special parser that just takes a list of strings 🤔

**Comment by G-Rath** [comment]
So I've been playing around with this a bit more (even though I was planning to merge it 😅) and found something interesting - if I parallelise the batch submissions, the _lower_ I make the batching size (so increasing the number of batches overall) the _faster_ we get 🤔

It's enough to at least shave a good 5-10 seconds off consistently in a directory with two lockfiles, though I think it's being made more noticeable by the fact that each lockfile is being processed in series - I'm going to see if I can hack together doing that in parallel.

**Comment by G-Rath** [comment]
Ok I'm going to land this so I can do #98 and land followup improvements/changes in their own PRs

**Pull request merged**
